name: Pull Requests

on:
  pull_request_target:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set up GCC
        run: sudo apt-get install -y make gcc build-essential

      - name: Build
        run: go build -v ./...

      - name: Test
        env: 
          BIER: ${{ secrets.bier }}
        run: go test -v -coverprofile=coverage.out ./...
